"use client"
import './globals.css'
import { Inter } from 'next/font/google'

import { getFullnodeUrl } from '@mysten/sui.js/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import AuthProvider from "./hooks/AuthProvider";
import { NavbarProvider } from '../../context/NavbarContext';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import {WalletProvider} from '@suiet/wallet-kit';
import '@suiet/wallet-kit/style.css';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
      {/* <AuthProvider> */}
      <QueryClientProvider client={queryClient}>
			
				<WalletProvider>
          <NavbarProvider>
            <AntdRegistry>
              {children}
            </AntdRegistry>
          </NavbarProvider>
        </WalletProvider>
			
		</QueryClientProvider>
    {/* </AuthProvider> */}
      </body>
    </html>
  )
}